# Numpy

 - NumPy is a package which is more important to study when you’re learning data science
 - This library provides you an "array" data structure which is more proficient than  Python lists
 - It provides faster access in reading and writing items.
 - NumPy can also be used as an efficient multi-dimensional container of generic data


In [29]:
my_list=[101,102,103,104,105]

In [30]:
import numpy as np

In [31]:
myndarray=np.array(my_list)

In [32]:
print(myndarray)

[101 102 103 104 105]


In [33]:
#arange fucntion
ndarray2=np.arange(2,10)
ndarray2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
nda3=np.zeros(5)
nda3

array([0., 0., 0., 0., 0.])

In [35]:
nda3=np.zeros((4,3))
nda3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [37]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
np.linspace(0,20,5) # in linspace last value is also considered i.e difference from arange

array([ 0.,  5., 10., 15., 20.])

In [39]:
np.eye(5) #identity matrix 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.random.randint(5,20)

10

In [41]:
np.random.randint(5,20,10)

array([13,  9, 13, 18, 10, 15, 18, 18, 18,  7])

In [42]:
np.random.rand(5)

array([0.18219554, 0.87082478, 0.11763879, 0.49336473, 0.41087005])

In [43]:
np.random.rand(2,4)

array([[0.91794861, 0.85025436, 0.95667535, 0.31245739],
       [0.25999546, 0.47604024, 0.43929   , 0.46452413]])

In [44]:
np.random.randn(5)

array([-0.5899527 ,  0.38746569, -1.68119609,  0.97220426,  0.22588109])

In [45]:
np.random.randn(3,5)

array([[-0.88468377,  0.03224911, -1.43456849,  0.60515022,  1.51146134],
       [ 1.29161536,  0.60348455, -1.17606357, -0.55096099,  1.92156607],
       [ 0.9838181 ,  0.64363124, -1.10559461,  0.50067094, -0.26553677]])

reshape

In [46]:
a1=np.arange(30)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [47]:
a1=a1.reshape(5,6)

In [48]:
a1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [49]:
a1.max()

29

In [50]:
a1.min()

0

In [51]:
a1.argmax()

29

In [52]:
a1.argmin()

0

In [53]:
a1.shape

(5, 6)

In [54]:
a1.dtype

dtype('int32')

In [55]:
a1.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

Numpy Indexing ans selection

In [56]:

l1=list[2,5,9,7,10,25,30,45]
a2=np.array(l1)

TypeError: 'type' object is not subscriptable

Broadcast

In [ ]:
ra1=np.random.randint(0,10,8)
ra1

In [ ]:
ra1*2

In [ ]:
ra2=ra1[3:7]
ra2

In [ ]:
ra2[:]=100
ra2

In [ ]:
m1=np.array(([50,200,5,10],[0,35,50,15],[25,100145,20],[10,20,30,50]))
m1

In [ ]:
m1[1]

In [ ]:
sample_matrix = np.array(([50,200,5,10],[10,35,50,15],[25,100,145,120],[105,25,65,80]))
sample_matrix

In [ ]:
sample_matrix[:,1]

In [ ]:
sample_matrix[3:,1:]

In [ ]:
array1=np.arange(0,31)
array1

In [ ]:
array1[array1<10].shape

In [ ]:
array1+array1

In [ ]:
array1*array1

### universal functions in numpy

In [ ]:
np.sqrt(array1)

In [ ]:
np.ext(array1)

In [ ]:
np_log=np.log(array1)

In [ ]:
np.sin(array1)

In [ ]:
np.square(array1)

In [ ]:
np_log

In [ ]:
np.round(np_log,decimals=2)

In [ ]:
np.std(array1)

In [ ]:
np.var(array1)

In [ ]:
np.mean(array1)

In [ ]:
np.unique(array1)

In [ ]:
fr=np.array(['Banana',"mango","apple","kiwi","banana","kiwi","orange"])
fr

In [ ]:
np.unique(fr)

In [ ]:
for fruits in fr:
    print(fruits)

## linalg functions

In [57]:
m2=np.array([[10,20],[30,40]])
m2

array([[10, 20],
       [30, 40]])

In [58]:
np.linalg.inv(m2)

array([[-0.2 ,  0.1 ],
       [ 0.15, -0.05]])

In [59]:
np.trace(m2)

50

In [60]:
print(np.linspace(4,13,7))

[ 4.   5.5  7.   8.5 10.  11.5 13. ]


In [61]:
simple_list = [101,102,103,104,105,106,107,108,109,110]
simple_list

[101, 102, 103, 104, 105, 106, 107, 108, 109, 110]

In [62]:
np.array(simple_list)

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [63]:
simple_list_of_lists = [[10,11,12],[20,21,22],[30,31,32]]
simple_list_of_lists

[[10, 11, 12], [20, 21, 22], [30, 31, 32]]

In [64]:
np.array(simple_list_of_lists)

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

#There are multiple built-in methods to generate Arrays


arange
Return evenly spaced values within a given interval as input.

In [65]:
np.arange(0,20)         # Return values 0 to 19. Start value is 
#0 which is included, the stop value provided is 20 which is not included

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [66]:
np.arange(0,20,4)  

array([ 0,  4,  8, 12, 16])

In [67]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [68]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
np.empty((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

linspace
Return evenly spaced numbers over a specified interval.

In [72]:
np.linspace(0,20,5)    # Specify the start, stop and number values needed between them.
#Please note the stop value is also considered in this case

array([ 0.,  5., 10., 15., 20.])

In [73]:
np.linspace(0,20,100)

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

eye
Return a 2-D array with ones on the diagonal and zeros elsewhere. Also called an identity matrix

In [74]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Random
  ## Numpy has lots of options to create random numbered arrays:

- rand # Create an array of the given shape and populate it with 
- #random variables derived from a uniform distribution between [0, 1).

In [75]:
np.random.rand(5)

array([0.07000278, 0.88658172, 0.9182041 , 0.54848435, 0.23619684])

In [76]:
np.random.rand(3,2)

array([[0.55807917, 0.3264892 ],
       [0.07063722, 0.8142146 ],
       [0.3962462 , 0.07543284]])

randn
Return a variable (or a set of variables) from the "Standard Normal" distribution. Unlike rand which is from a uniform distribution:

A standard Normal Distribution has mean 0 and SD of 1 as we know.

In [77]:
np.random.randn(5)

array([-0.66904323, -1.58879215,  1.20964765, -0.6754749 ,  0.28555799])

In [78]:
np.random.randn(3,2)

array([[ 1.39200528, -0.79616377],
       [-0.67749297,  0.73853422],
       [-0.16179678,  0.01019555]])

randint
Return random integers from low (inclusive) to high (exclusive).

In [79]:
np.random.randint(5,20,7)

array([ 9, 16,  7,  7, 12, 14,  8])

In [80]:
sample_array = np.arange(30)
rand_array = np.random.randint(0,100,20)

In [81]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [82]:
rand_array

array([43,  5, 10, 77, 10, 65, 71, 70, 63, 63, 86, 72, 39, 50, 86, 47, 97,
       55, 10, 16])

In [83]:
sample_array.reshape((5,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [84]:
sample_array.max()

29

In [85]:
sample_array.min()

0

In [86]:
sample_array.mean()

14.5

In [87]:
sample_array.argmax()

29

In [88]:
rand_array.argmax()

16

In [89]:
rand_array.argmin()

1

In [90]:
sample_array.shape

(30,)

In [91]:
sample_array.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [92]:
sample_array.reshape(1,30).shape

(1, 30)

In [93]:
sample_array.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [94]:
sample_array.dtype

dtype('int32')

In [95]:
sample_array2 = np.random.randn(4,4)

sample_array2

array([[ 1.19556181,  0.85683952, -1.48873821,  0.33194994],
       [ 0.13679025,  0.28680397,  0.47625243,  0.66674171],
       [-0.75417529, -0.91429077,  1.07100198, -0.34936945],
       [-1.49430234, -0.49433685,  1.64973976,  0.15352871]])

In [96]:
sample_array2.T

array([[ 1.19556181,  0.13679025, -0.75417529, -1.49430234],
       [ 0.85683952,  0.28680397, -0.91429077, -0.49433685],
       [-1.48873821,  0.47625243,  1.07100198,  1.64973976],
       [ 0.33194994,  0.66674171, -0.34936945,  0.15352871]])

In [97]:
#Create a sample array with 11 values
sample_array = np.arange(10,21)

In [98]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [99]:
sample_array[3:11]

array([13, 14, 15, 16, 17, 18, 19, 20])

In [100]:
sample_array[[3,4,5,7]]

array([13, 14, 15, 17])

In [101]:
#Setting a fixed value 100 using index range (Broadcasting)
sample_array[1]=100

#Show
sample_array

array([ 10, 100,  12,  13,  14,  15,  16,  17,  18,  19,  20])

In [102]:
# Reset array, we shall see the need for reset
sample_array = np.arange(10,21)

#Show
sample_array


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [103]:
#Subsetting an array
subset_sample_array = sample_array[0:7]

#Output of the subset
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [104]:
#Change the values in the subset
subset_sample_array[:]=1001

#Show subset output again
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [105]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [106]:
sample_matrix = np.array(([50,200,5,10],[10,35,50,15],[25,100,145,120],[105,25,65,80]))

#Show output
sample_matrix

array([[ 50, 200,   5,  10],
       [ 10,  35,  50,  15],
       [ 25, 100, 145, 120],
       [105,  25,  65,  80]])

In [107]:
sample_matrix[1]

array([10, 35, 50, 15])

In [108]:
sample_matrix[1:,:3]

array([[ 10,  35,  50],
       [ 25, 100, 145],
       [105,  25,  65]])

In [109]:
#Set up a sample matrix
sample_matrix = np.array(([50,200,5,10,160],[170,10,35,50,15],[125,25,100,145,120],[100,105,25,65,80],[250,15,25,30,100]))

sample_matrix

array([[ 50, 200,   5,  10, 160],
       [170,  10,  35,  50,  15],
       [125,  25, 100, 145, 120],
       [100, 105,  25,  65,  80],
       [250,  15,  25,  30, 100]])

In [110]:
sample_matrix[:,(1,3)]

array([[200,  10],
       [ 10,  50],
       [ 25, 145],
       [105,  65],
       [ 15,  30]])

In [111]:
#Allows to retrieve in any order
sample_matrix[:,(3,1)]

array([[ 10, 200],
       [ 50,  10],
       [145,  25],
       [ 65, 105],
       [ 30,  15]])

In [112]:
simple_array = np.arange(1,31)
simple_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [113]:
simple_array <10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [114]:
simple_array[simple_array<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
simple_array[simple_array>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [116]:
a = 11
simple_array[simple_array>a]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30])

In [117]:
simple_array = np.arange(0,21)

In [118]:
simple_array+simple_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40])

In [119]:
simple_array*simple_array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400])

In [120]:
simple_array-simple_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [121]:
sample_array/sample_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [122]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [123]:
sample_array**2

array([1002001, 1002001, 1002001, 1002001, 1002001, 1002001, 1002001,
           289,     324,     361,     400], dtype=int32)

In [124]:
np.sqrt(sample_array)

array([31.63858404, 31.63858404, 31.63858404, 31.63858404, 31.63858404,
       31.63858404, 31.63858404,  4.12310563,  4.24264069,  4.35889894,
        4.47213595])

In [125]:
np.exp(sample_array)

C:\Users\sonali\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.


array([           inf,            inf,            inf,            inf,
                  inf,            inf,            inf, 2.41549528e+07,
       6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [126]:
np.log(sample_array)

array([6.90875478, 6.90875478, 6.90875478, 6.90875478, 6.90875478,
       6.90875478, 6.90875478, 2.83321334, 2.89037176, 2.94443898,
       2.99573227])

In [127]:
np.max(sample_array)

1001

In [128]:
np.cos(sample_array)

array([-0.39194043, -0.39194043, -0.39194043, -0.39194043, -0.39194043,
       -0.39194043, -0.39194043, -0.27516334,  0.66031671,  0.98870462,
        0.40808206])

In [129]:
array_2 = np.random.randn(5,5)
array_2

array([[ 1.1109978 ,  0.49183035,  0.0135725 ,  0.23499172, -0.47251706],
       [-1.92630126, -0.05295621,  1.28045066, -0.5055381 ,  0.97403565],
       [ 0.70459072, -0.55954902, -0.61208815,  0.86651277,  1.2107925 ],
       [-0.02239891,  1.02906893, -1.94037261,  0.52275302, -0.33873267],
       [-0.0021888 , -1.45562322,  1.04006775, -1.82331671, -0.64775796]])

In [130]:
np.round(array_2,decimals =2)

array([[ 1.11,  0.49,  0.01,  0.23, -0.47],
       [-1.93, -0.05,  1.28, -0.51,  0.97],
       [ 0.7 , -0.56, -0.61,  0.87,  1.21],
       [-0.02,  1.03, -1.94,  0.52, -0.34],
       [-0.  , -1.46,  1.04, -1.82, -0.65]])

In [131]:
np.mean(array_2)

-0.03518705255161371

In [132]:
#Using the unique function
sports = np.array(['Golf', 'Cricket', 'Football', 'Football','Cricket','cricket','Basketball', 'Baseball'])

np.unique(sports)

array(['Baseball', 'Basketball', 'Cricket', 'Football', 'Golf', 'cricket'],
      dtype='<U10')

In [133]:
#Create a simple array
simple_array = np.arange(11)

simple_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
#Save array on hard disk in binary format (file extension is .npy)
np.save('array1',simple_array)

In [135]:
#Change arr
simple_array = np.arange(21)
#Show
simple_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [136]:
#Lets see the original saved copy - This does not get affected by the changes we have made to the simple_array
np.load('array1.npy')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [137]:
#Saving multiple arrays into a zip file using savez (file extension is .npz and not .npy)
np.savez('2_arrays.npz',a=simple_array,b=simple_array)

In [138]:
#Now loading multiple arrays using load
archived_arrays = np.load('2_arrays.npz')

#Show
archived_arrays['a']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [139]:
#Saving the arrays as text files

simple_array2 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.savetxt('my_text.txt',simple_array2,delimiter=',')

In [140]:
simple_array2 = np.loadtxt('my_text.txt',delimiter = ',')

simple_array2

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14.]])

*****END*********